# Generated by Django 4.2.16 on 2025-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=10),
        ),
    ]
