# Generated by Django 4.2.16 on 2025-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0002_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
