# Generated by Django 4.2.16 on 2025-12-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0003_booking_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
