# Generated by Django 4.2.16 on 2025-12-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0004_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
