# Generated by Django 4.2.16 on 2025-10-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0002_booking_booking_type'),
        ('checkout', '0006_orderlineitem_tour_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='taproom_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taproom.booking'),
        ),
    ]
