# Generated by Django 4.2.16 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
