# Generated by Django 4.2.16 on 2025-10-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taproom', '0002_booking_booking_type'),
        ('bag', '0003_alter_cartitem_tour_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='taproom_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taproom.booking'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('tour', 'Tour'), ('taproom', 'Taproom Booking')], max_length=10),
        ),
    ]
